name: Rule Update & DNS Validation

on:
  schedule:
    - cron: "0 0,6,12,18 * * *"  # 每天在 0, 6, 12, 18 UTC 执行
  workflow_dispatch:

jobs:
  update_and_validate_rules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # 使用 Python 3.x 版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # 安装项目中的依赖

    - name: Download and merge rules from urls.txt
      run: |
        python3 download_and_merge_rules.py  # 下载并合并规则的脚本

    - name: Split rules and start DNS validation
      run: |
        python3 split_and_validate.py  # 分片并验证 DNS 的脚本

    - name: Upload logs
      uses: actions/upload-artifact@v4  # 使用最新的 v4 版本
      with:
        name: validation-logs
        path: ./logs/*  # 确保日志保存到 logs 目录中
