name: Rule Update & DNS Validation

on:
  schedule:
    - cron: "0 0,6,12,18 * * *"  # 每天四次，分别是 0、6、12、18 UTC
  workflow_dispatch:

jobs:
  update_and_validate_rules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download and merge rules from urls.txt
      run: |
        python3 download_and_merge_rules.py  # 下载并合并规则

    - name: Split rules and start DNS validation
      run: |
        python3 split_and_validate.py  # 分片并验证 DNS

    - name: Upload logs
      uses: actions/upload-artifact@v4  # 使用最新的 v4 版本
      with:
        name: validation-logs
        path: ./logs/*  # 上传 logs 文件夹中的所有日志
